# config.yaml

planet:
  name: HD106315c       # needs to match directory where Stage 3 files are stored, i.e. 'TOI1130b_NIRSPEC'
  period:     21.05704     # fixed 
  duration:   0.19325       # prior
  t0:         60474.312    # prior, needs to be estimated from whitelight glance
  b:          0.52         # prior
  rprs:      0.03086       # prior

stellar:
  feh:   -0.27
  teff:  6364
  logg:  4.48
  ld_model: "stagger"
  ld_data_path: "../exotic_ld_data"

instrument: 'MIRI/LRS'
order: None 
nrs: 1              # 1 or 2
path: 'HD106315'
input_dir: 'HD106315_MIRI' # where the calints files are stored relative to path
output_dir: 'LRS_FIXEDLD_EXPRAMP' # where the output files are stored relative to path

resolution_bins:
  high: 40 # nm resolution to bin spectroscopic curves
  low:  10 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]

flags:
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: False # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: True
  need_lowres: False # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended

outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals

host_device: "gpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31



