# config.yaml

planet:
  name: HATP11b       # needs to match directory where Stage 3 files are stored, i.e. 'TOI1130b_NIRSPEC'
  period:     4.887802443     # fixed 
  duration:   0.09815       # prior
  t0:         60895.9922    # prior, needs to be estimated from whitelight glance
  b:          0.227         # prior
  rprs:      0.058993       # prior

stellar:
  feh:   0.31
  teff:  4780
  logg:  4.563
  ld_model: "mps1"
  ld_data_path: "../exotic_ld_data"

instrument: 'NIRISS/SOSS'
order: 1
nrs: None              # 1 or 2
path: 'HATP11'
input_dir: 'HATP11b_NIRISS' # where the calints files are stored relative to path
output_dir: 'ORDER1_LINEAR_INTERPLD' # where the output files are stored relative to path
fits_file: 'xyz.fits'

resolution_bins:
  high: 400 # nm resolution to bin spectroscopic curves
  low:  40 # nm resolution to bin spectroscopic curves [optional: not triggered if not low-res]

flags:
  detrending_type: 'linear'  # Type of detrending: 
                                # linear = offset + linear with time term,
                                # gp = whitelight gp on CPU which is subtracted from multiwavelength, and then linear on GPU, 
                                # explinear = linear with Aexp(-t/tau) ramp. 
  interpolate_trend: False # Option to interpolate trend coefficients from low res to high res | defaults to False
  interpolate_ld: True # Option to interpolate LD coefficients from low res ot high res | defaults to false
  fix_ld: False
  need_lowres: True # Option to fit low res first if other flags are false to clip spectroscopic outliers, reccommended

outlier_clip:
  whitelight_sigma:   4 # sigma to clip outliers from whitelight residual 
  spectroscopic_sigma: 4 # sigma to clip outliers from spectroscopic residuals

host_device: "cpu"      # 'gpu' or "cpu" | reminder, if using gpu you need jax[cuda]<=0.4.31, cpu needs jax[cpu]<=0.4.31



